// <auto-generated />
using System;
using MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231217134826_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC.Models.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65c35b53-520c-401a-9501-6d9a4bbdb1a4"),
                            Description = "Apples flagskibs-smartphone med en kraftfuld A15 Bionic-chip og avanceret kamera.",
                            Name = "iPhone 13 Pro"
                        },
                        new
                        {
                            Id = new Guid("0664de50-3698-433d-b060-2013b7a62bf7"),
                            Description = "Samsungs premium-telefon med en imponerende skærm, alsidigt kamera og kraftfuld ydeevne.",
                            Name = "Samsung Galaxy S21 Ultra"
                        },
                        new
                        {
                            Id = new Guid("31988d6d-e555-452d-98fe-9e844b4c760a"),
                            Description = "Googles smartphone kendt for dens exceptionelle kamerakapaciteter og AI-drevne funktioner.",
                            Name = "Google Pixel 6 Pro"
                        },
                        new
                        {
                            Id = new Guid("2af31e92-6f95-4cb4-b4cf-dcff6a5e6115"),
                            Description = "OnePlus' flagskibs-enhed med hurtig ydeevne, en glat skærm og fantastiske kameraer.",
                            Name = "OnePlus 9 Pro"
                        },
                        new
                        {
                            Id = new Guid("45696051-17ab-4460-a47f-21586674ea0f"),
                            Description = "Xiaomis high-end telefon med et kvalitetskamera-setup og en smuk AMOLED-skærm.",
                            Name = "Xiaomi Mi 11 Ultra"
                        },
                        new
                        {
                            Id = new Guid("16ec312b-9c3f-45db-ba3a-655f2f7bd534"),
                            Description = "Huaweis premium smartphone med et kraftfuldt kamera-system og imponerende design.",
                            Name = "Huawei P50 Pro"
                        },
                        new
                        {
                            Id = new Guid("83f4e414-72d8-43f2-9742-665a05bb9b57"),
                            Description = "Sonys flagskibs-enhed kendt for dens 4K OLED-skærm og avancerede kamerafunktioner.",
                            Name = "Sony Xperia 1 III"
                        },
                        new
                        {
                            Id = new Guid("fb996825-0dc5-406a-a275-016404635fba"),
                            Description = "OnePlus' mellemklasse-telefon med god ydeevne og et kompetent kamera-system.",
                            Name = "OnePlus Nord 2"
                        },
                        new
                        {
                            Id = new Guid("2cd2e696-36f6-4368-b346-449a7a792490"),
                            Description = "Realmes overkommelige smartphone med et unikt design og god ydelse.",
                            Name = "Realme GT Master Edition"
                        },
                        new
                        {
                            Id = new Guid("fbb8814e-54f5-4d33-85c4-36e1f3a037de"),
                            Description = "Motorolas telefon med en skærm med høj opdateringshastighed og god batterilevetid.",
                            Name = "Motorola Edge 20 Pro"
                        },
                        new
                        {
                            Id = new Guid("d206ba73-794a-4f4d-b5a6-a73c86638f5a"),
                            Description = "Samsungs foldbare smartphone med imponerende skærmteknologi og alsidig brug.",
                            Name = "Samsung Galaxy Z Fold 3"
                        },
                        new
                        {
                            Id = new Guid("e419bb07-9b2c-4640-bcb4-62607383cbc9"),
                            Description = "Googles mellemklasse-smartphone med et pålideligt kamera og lang batterilevetid.",
                            Name = "Google Pixel 5a"
                        },
                        new
                        {
                            Id = new Guid("e87defdc-9f56-4da1-a1c0-64316c00db85"),
                            Description = "OnePlus' tidligere flagskibs-enhed med god ydeevne og hurtig opladning.",
                            Name = "OnePlus 8T"
                        },
                        new
                        {
                            Id = new Guid("d2023d12-b9b3-4d49-9306-56b59365f22a"),
                            Description = "Xiaomis prisvenlige telefon med en god skærm og solid ydeevne.",
                            Name = "Xiaomi Redmi Note 10"
                        },
                        new
                        {
                            Id = new Guid("17a26cf1-d574-4ff8-8202-f4e4d007b4c7"),
                            Description = "Huaweis avancerede smartphone med kraftfuld processor og avanceret kamera.",
                            Name = "Huawei Mate 40 Pro"
                        },
                        new
                        {
                            Id = new Guid("9c57be99-eadf-47e8-8ca9-ec1f2e0a668f"),
                            Description = "Sonys kraftfulde telefon kendt for sit kompakte design og imponerende skærm.",
                            Name = "Sony Xperia 5 III"
                        },
                        new
                        {
                            Id = new Guid("b12c5bb0-cb60-4ff9-a56f-731bf213be08"),
                            Description = "Realmes budgetvenlige smartphone med anstændige specifikationer og god batterilevetid.",
                            Name = "Realme Narzo 50A"
                        },
                        new
                        {
                            Id = new Guid("d8af5558-3d60-4140-833c-225abfbfe828"),
                            Description = "Motorolas telefon kendt for sin lange batterilevetid og pålidelige ydeevne.",
                            Name = "Motorola Moto G Power"
                        },
                        new
                        {
                            Id = new Guid("d307b89d-9371-4465-af89-11c8f9806e65"),
                            Description = "Nokias robuste telefon designet til at modstå barske forhold og holde længe.",
                            Name = "Nokia XR20"
                        },
                        new
                        {
                            Id = new Guid("879adddc-5b3b-40fd-a92a-f96dbadb5bef"),
                            Description = "Asus' kompakte smartphone med stærk ydeevne og fremragende skærmkvalitet.",
                            Name = "Asus Zenfone 8"
                        },
                        new
                        {
                            Id = new Guid("bb7bf306-5868-4106-a566-dab617750626"),
                            Description = "Xiaomis prisvenlige smartphone med en god skærm og lang batterilevetid.",
                            Name = "Xiaomi Redmi 10"
                        },
                        new
                        {
                            Id = new Guid("f94a591b-eefd-4e16-a4e8-f99ba3ed4e64"),
                            Description = "Motorolas telefon med en stylus-pen og pålidelig ydeevne.",
                            Name = "Motorola Moto G Stylus"
                        },
                        new
                        {
                            Id = new Guid("ff1d5953-3cf9-4114-add1-fe959fb915f5"),
                            Description = "Realmes hurtige smartphone med avancerede specifikationer og stilfuldt design.",
                            Name = "Realme GT Neo 2"
                        },
                        new
                        {
                            Id = new Guid("5896effa-75da-4b99-9ad4-87953c1e6dfa"),
                            Description = "OnePlus' 5G-mid-range telefon med hurtig ydeevne og et slankt design.",
                            Name = "OnePlus Nord CE 5G"
                        },
                        new
                        {
                            Id = new Guid("e2a02188-1f1e-4952-940d-e1151dd5d9d7"),
                            Description = "Sonys mellemklasse-smartphone med lang batterilevetid og god skærmkvalitet.",
                            Name = "Sony Xperia 10 III"
                        },
                        new
                        {
                            Id = new Guid("a90e6a18-8b7d-4a05-b44b-9f279c55256c"),
                            Description = "Samsungs 5G-telefon med en skarp skærm og alsidige funktioner.",
                            Name = "Samsung Galaxy A52s 5G"
                        },
                        new
                        {
                            Id = new Guid("b72358f4-b72d-42fe-ba61-a6bd8509976b"),
                            Description = "Googles prisvenlige smartphone med god kamerateknologi og brugervenlig oplevelse.",
                            Name = "Google Pixel 4a"
                        },
                        new
                        {
                            Id = new Guid("7d63bd70-b2a8-4093-95f6-276fb311ef84"),
                            Description = "Xiaomis telefon med stærk ydeevne og imponerende batterilevetid.",
                            Name = "Xiaomi Poco X3 Pro"
                        },
                        new
                        {
                            Id = new Guid("61f001c7-efc8-49cc-aafc-4669ab951a6a"),
                            Description = "Motorolas budgetvenlige smartphone med grundlæggende funktioner og lang batterilevetid.",
                            Name = "Motorola Moto E7"
                        },
                        new
                        {
                            Id = new Guid("d3f6704c-4864-4ed4-8d10-5536e5f201e1"),
                            Description = "Nokias prisvenlige 5G-smartphone med en pålidelig ydeevne og robust design.",
                            Name = "Nokia G50"
                        },
                        new
                        {
                            Id = new Guid("e1527334-20ee-4272-92c4-eaffcf7c0243"),
                            Description = "Asus' gaming-telefon med kraftfuld hardware og avancerede spilfunktioner.",
                            Name = "Asus ROG Phone 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
